### ISSUE TITLE
redirect: does not work

### ISSUE THREAD

**Issue by vba** [tomcz/spring-stringtemplate#1]
Hi,

redirect: does not work !

**Comment by tomcz** [comment]
Hah, I've actually been waiting for someone to notice.

"redirect:" and "forward:" view names are actually handled by the org.springframework.web.servlet.view.UrlBasedViewResolver (which the Freemarker and Velocity view resolvers extend). The UrlBasedViewResolver simply resolves these view names to either a org.springframework.web.servlet.view.RedirectView or a org.springframework.web.servlet.view.InternalResourceView after stripping off the prefix.

I did not want to use the UrlBasedViewResolver as the base class for my StringTemplateViewResolver since I have no use for view caching at the level of the resolver (if necessary I'd prefer to use StringTemplate's caching setup) and its view creation workflow does not play well with the way I want to use StringTemplate.

There are a couple of options to get redirects and forwards working for you right now:
1. Use the RedirectView and InternalResourceView classes directly rather than creating view names with "redirect:" or "forward:" prefixes. RedirectView is very powerful and you can set per-redirect context-relative URLs, 302 vs 303 redirects, and whether to append model attributes as query string parameters.
2. org.springframework.web.servlet.view.InternalResourceViewResolver extends the UrlBasedViewResolver and can therefore resolve view names with "redirect:" and "forward:" prefixes. Both the StringTemplateViewResolver and InternalResourceViewResolver implement the ordered interface. If you set the order property on the StringTemplateViewResolver as 1 and on the InternalResourceViewResolver as 2 in your spring-servlet.xml configuration, then any views that the StringTemplateViewResolver cannot resolve (ie. URLs with "redirect:" and "forward:" prefixes) will wind up being handed by the next view resolver (ie. the InternalResourceViewResolver). For an example of how this is actually done please take a look at the spring-servlet.xml in the src/test/webapp/WEB-INF folder of the project.

**Comment by vba** [comment]
Hi, 

Thanks, I've found an another solution that could be simplified if StringTemplateViewResolver#resolveViewName will return View instead of StringTemplateView. Otherwise my solution is following:

public MyView resolveViewName(String viewName, Locale locale) {

```
if (viewName.startsWith(UrlBasedViewResolver.REDIRECT_URL_PREFIX)) {
    String redirectUrl = viewName.substring(UrlBasedViewResolver.REDIRECT_URL_PREFIX.length());
    return new SplayceView().bindRedirectView(new RedirectView(redirectUrl,true));
}
if (viewName.startsWith(UrlBasedViewResolver.FORWARD_URL_PREFIX)) {
    String forwardUrl = viewName.substring(UrlBasedViewResolver.FORWARD_URL_PREFIX.length());
    return new SplayceView().bindInternalResourceView(new InternalResourceView(forwardUrl));
}

try {
    WebStringTemplate template = createTemplate(viewName);
    SplayceView view = createView();
    setupView(template, view);
    return view;

} catch (Exception e) {
    return null;
}
```

}

And in my View class I've to check if UrlBasedViewResolver/InternalResourceView is set :

public void render(Map<String, ?> model, HttpServletRequest request, HttpServletResponse response) throws IOException {

```
if (internalResourceView != null) {
    render(internalResourceView,model,request,response); 
    return;
} else if (redirectView != null) {
    render(redirectView,model,request,response);
    return;
}
```

.....
}

To simplify this resolveViewName must return View type.

An another question, it would be possible to make StringTemplateDecoratorServlet more extensible ? Because a lot of fields/methods of this class are private. 
Otherwise I've introduced message/error elements into templates to permit i18n & errors management. If you are interested I can share my modifications with you.

**Comment by tomcz** [comment]
Interesting. That's definitely another way to do it if you want to only have a single ViewResolver per application.

What would you like to override in the StringTemplateDecoratorServlet? Do you want to be able to provide your own version of a ViewResolver?

**Comment by vba** [comment]
For example to get i18n and errors available in my templates I've extended StringTemplateView by my own View class (by heritage), all works fine for simple templates. But I can not put this goodies in decorators without complete redefinition of the decorator servlet, because inside you use StringTemplateView (method doGet) and I would like to use my extended view class.

**Comment by vba** [comment]
Normally it's my goal to have one "automated" view resolver per application.

**Comment by tomcz** [comment]
I've committed version 1.2 - more configurable StringTemplateDecoratorServlet and full support for Spring messages and themes.
