### ISSUE TITLE
Rendering model data in sitemesh template

### ISSUE THREAD

**Issue by cymantic** [tomcz/spring-stringtemplate#6]
I'm looking for a way to have information generated in the model rendered as part of the sitemesh template...

e.g. if we have some navigation I want to indicate what the current page is, but only have the navigation in the sitemesh template.

I can generate the information easily enough in the controller (although this feels like the wrong place too), but can't access this navigation model in the sitemesh template.

**Comment by tomcz** [comment]
That is because sitemesh is not aware of spring controllers, views or models. It is a generic output filter for any servlet output stream and therefore any web framework. I don't see the purpose of this library to go beyond that since I do like the separation of concerns between content and decoration. If you are looking for composition you probably should look at an alternative mechanism to sitemesh - perhaps something like tiles. If you still want sitemesh to use certain values provided by spring you can provide them by a couple of ways:
1. add them to the request as attributes in either your spring controller, or in the postHandle method of a spring HandlerInterceptor
2. pass them as meta tags or divs in your rendered spring view and then use the div extraction capabilities of sitemesh - this is very powerful and your sitemesh decorators can become server-side mashup engines, but you do have to do more work. 
There may be other ways to do this, but I don't usually go beyond 1 or 2.
